services:
    - docker

before_install:
    - docker -v
    # Stop the postgres instance travis sets up automatically
    - sudo /etc/init.d/postgresql stop
    - sudo service mysql stop

script: ./scripts/run-tests-docker.sh
