name: test-planshboard
on: [ push ]
jobs:
    test-frontend-code:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: '16'
            -   name: Install dependencies
                run: npm install
            -   name: Run tests
                run: npm test

    test-backend-code:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: github_password
                    POSTGRES_USER: github_user
                    POSTGRES_DB: planshboard_test
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v2
                with:
                    java-version: '11'
                    distribution: 'adopt'

            -   name: Install dependencies
                run: mvn dependency:go-offline -q
            -   name: Run tests
                run: mvn test    -Ddb.url=$DATABASE_URL -Ddb.username=$DATABASE_USER -Ddb.password=$DATABASE_PASSWORD -Dspring.datasource.username=$DATABASE_USER -Dspring.datasource.password=$DATABASE_PASSWORD -Dspring.datasource.url=$DATABASE_URL -Dspring.flyway.enabled='false'
                env:
                    DATABASE_URL: jdbc:postgresql://localhost:5432/planshboard_test
                    DATABASE_USER: github_user
                    DATABASE_PASSWORD: github_password

